#! /usr/bin/env python3

# Creates a diff file with the differences between the original PO
# translation files and the ones generated by change_tr_shortcuts.py.
#
# Language must be indicated.

import os
import sys
import difflib


def find_vcs_root(dirs=(".svn", ".git"), default=None):
    """
    Returns the repo root dir.
    :param dirs: dirs to look for.
    :param default: value to return if not found.
    :return: repo root dir.
    """
    prev, test = None, os.path.abspath(os.path.dirname(__file__))
    while prev != test:
        if any(os.path.isdir(os.path.join(test, d)) for d in dirs):
            return test
        prev, test = test, os.path.abspath(os.path.join(test, os.pardir))
    return default


root_dir = find_vcs_root()

# Preliminary checks:
if root_dir is None:
    print('Repository not found. Script must be in a repo subfolder.')
elif len(sys.argv) != 2:
    print("""\nUsage: diff_tr_shortcuts.py <LANGUAGE>

    Examples: diff_tr_shortcuts.py es
              diff_tr_shortcuts.py fr\n""")
elif not os.path.isdir(os.path.join('new_locale', sys.argv[1])):
    print("'new_locale/" + sys.argv[1] + "' folder not found.")
else:  # All OK
    fdiff = open('diff_' + sys.argv[1] + '.txt', 'wt')
    # Main loop:
    for info_dir in os.walk(os.path.join('new_locale', sys.argv[1])):
        for fname in info_dir[2]:
            path_out = os.path.abspath(os.path.join(info_dir[0], fname))
            path_in = os.path.join(root_dir, path_out[path_out.find('locale'):])
            f_out = open(path_out, 'rt')
            f_in = open(path_in, 'rt')
            str_out = f_out.readlines()
            str_in = f_in.readlines()
            diff = difflib.context_diff(str_in, str_out,
                                        fromfile=path_in, tofile=path_out, n=0)
            for di in diff:
                fdiff.write(di)
            f_out.close()
            f_in.close()
            fdiff.write('\n\n\n')
    fdiff.close()
