#! /usr/bin/env python3

# Shows the differences between the original RST manual files
# and the ones generated by change_man_shortcuts.py.

import os
import difflib


def find_vcs_root(dirs=(".svn", ".git"), default=None):
    """
    Returns the repo root dir.
    :param dirs: dirs to look for.
    :param default: value to return if not found.
    :return: repo root dir.
    """
    prev, test = None, os.path.abspath(os.path.dirname(__file__))
    while prev != test:
        if any(os.path.isdir(os.path.join(test, d)) for d in dirs):
            return test
        prev, test = test, os.path.abspath(os.path.join(test, os.pardir))
    return default


root_dir = find_vcs_root()

if not os.path.isdir('new_manual'):
    print('new_manual folder not found.')
else:
    # Main loop:
    for info_dir in os.walk('new_manual'):
        for fname in info_dir[2]:
            path_out = os.path.abspath(os.path.join(info_dir[0], fname))
            path_in = os.path.join(root_dir, path_out[path_out.find('manual'):])
            f_out = open(path_out, 'rt')
            f_in = open(path_in, 'rt')
            str_out = f_out.readlines()
            str_in = f_in.readlines()
            diff = difflib.context_diff(str_in, str_out,
                                        fromfile=path_in, tofile=path_out, n=0)
            for di in diff:
                print(di, end='')
            f_out.close()
            f_in.close()
